# Generated by Django 6.1 on 2026-08-23 13:07

import django.core.validators
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_seed_repair_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemphoto',
            name='image',
            field=models.FileField(upload_to=inventory.models.item_photo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='locationphoto',
            name='image',
            field=models.FileField(upload_to=inventory.models.location_photo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='repairphoto',
            name='image',
            field=models.FileField(upload_to=inventory.models.repair_photo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'pdf'])]),
        ),
    ]
