# Generated by Django 6.1 on 2026-08-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_spare'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Value of this spares kit, in $, if known.', max_digits=10),
        ),
    ]
