# Generated by Django 6.1 on 2026-08-29 03:23

import django.core.validators
import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_spare_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=inventory.models.spare_photo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'pdf'])])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_receipt', models.BooleanField(default=False, help_text='This is a purchase receipt, not a photo of the spare.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventory.spare')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
    ]
