# Generated by Django 6.1 on 2026-08-29 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_sparephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit, in $, if known. Useful for insurance/valuation.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='spare',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Price per unit, in $, if known.', max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.unit'),
        ),
        migrations.AddField(
            model_name='spare',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spares', to='inventory.unit'),
        ),
    ]
