# Generated by Django 6.1 on 2026-08-29 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_unit_alter_inventoryitem_value_alter_spare_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='value',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='spare',
            old_name='value',
            new_name='unit_price',
        ),
    ]
