# Generated by Django 6.1 on 2026-08-29 03:44

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_seed_units'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
    ]
