# Generated by Django 6.1 on 2026-08-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_unit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Value of this location itself (e.g. the vessel's hull, or a structure like built-in shelving), in $, if known. Leave blank for most locations — this is separate from the value of what's stored here.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='locationphoto',
            name='is_receipt',
            field=models.BooleanField(default=False, help_text='This is a purchase/valuation receipt, not a photo of the location.'),
        ),
    ]
