# Generated by Django 6.1 on 2026-08-29 04:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_location_value_locationphoto_is_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Usually a whole count, but can be fractional (e.g. 4.5) when tracking by a unit like L or kg.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='repairconsumeditem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='spare',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Usually a whole count, but can be fractional (e.g. 4.5) when tracking by a unit like L or kg.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
