# Generated by Django 6.1 on 2026-09-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_vendor_job_partrequirement_proposaloption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposaloption',
            name='ordered_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total price actually paid for ordered_quantity, in $ — prefilled from the listed price but editable if it changed.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='proposaloption',
            name='ordered_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='How many units were actually ordered for ordered_price.', max_digits=10, null=True),
        ),
    ]
