# Generated by Django 6.1 on 2026-09-24 06:51

import django.core.validators
import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_proposaloption_ordered_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(blank=True, help_text="The manual's own item number within this section, e.g. '12-1'.", max_length=20)),
                ('bom_level', models.PositiveSmallIntegerField(blank=True, help_text="The manual's own BOM indent level (its 'Lev.' column) — unrelated to the catalog section tree depth above.", null=True)),
                ('part_number', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('quantity_note', models.CharField(blank=True, help_text='Quantity per engine/equipment variant, as printed in the manual (free text, since variant columns differ by catalog).', max_length=200)),
                ('remarks', models.CharField(blank=True, help_text="The manual's own remarks/flag column (e.g. superseded, interchangeable).", max_length=100)),
            ],
            options={
                'verbose_name': 'catalog part',
                'verbose_name_plural': 'catalog parts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CatalogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(help_text="e.g. 'Fig.27 COOLING FRESH WATER PUMP'.", max_length=200)),
                ('fig_number', models.CharField(blank=True, help_text="The catalog's own figure/section number, if it has one — used to order sections.", max_length=20)),
                ('page_number', models.PositiveIntegerField(blank=True, help_text='Page in the source PDF this section starts on, for the "open manual page" link.', null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'catalog section',
                'verbose_name_plural': 'catalog sections',
            },
        ),
        migrations.CreateModel(
            name='CatalogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('model_code', models.CharField(blank=True, help_text='Engine/equipment model this catalog covers, e.g. 4JH3E.', max_length=100)),
                ('file', models.FileField(upload_to=inventory.models.catalog_source_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='catalog_part',
            field=models.ForeignKey(blank=True, help_text='The parts-catalog entry this item matches, if you have one on file.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='inventory.catalogpart'),
        ),
        migrations.AddField(
            model_name='partrequirement',
            name='catalog_part',
            field=models.ForeignKey(blank=True, help_text='The parts-catalog entry this requirement matches, if you have one on file.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_requirements', to='inventory.catalogpart'),
        ),
        migrations.AddField(
            model_name='catalogpart',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='inventory.catalogsection'),
        ),
        migrations.AddField(
            model_name='catalogsection',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='inventory.catalogsource'),
        ),
    ]
