# Generated by Django 6.1 on 2026-09-24 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_catalogpart_catalogsection_catalogsource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequirement',
            name='rfq_vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor to request a quote from for this part — separate from ProposalOption.vendor, which is for a specific priced listing once you have one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_requirements', to='inventory.vendor'),
        ),
        migrations.CreateModel(
            name='Rfq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='inventory.job')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='inventory.vendor')),
            ],
            options={
                'verbose_name': 'RFQ',
                'verbose_name_plural': 'RFQs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RfqLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_lines', to='inventory.partrequirement')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.rfq')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('rfq', 'requirement')},
            },
        ),
    ]
