# Generated by Django 6.1 on 2026-09-28 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_partrequirement_rfq_vendor_rfq_rfqline'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="The catalog's own column letter/code, e.g. 'A'.", max_length=10)),
                ('name', models.CharField(help_text="e.g. '4JH3E'.", max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.catalogsource')),
            ],
            options={
                'ordering': ['catalog', 'order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CatalogPartFitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('from_identifier', models.CharField(blank=True, help_text='First serial/hull number (or year) this applies to. Blank = from the first one.', max_length=50)),
                ('to_identifier', models.CharField(blank=True, help_text='Last serial/hull number (or year) this applies to. Blank = no end.', max_length=50)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='inventory.catalogpart')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='inventory.catalogvariant')),
            ],
            options={
                'verbose_name': 'catalog part fitment',
                'ordering': ['part', 'variant__order', 'from_identifier'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Main engine'.", max_length=200)),
                ('serial', models.CharField(blank=True, help_text='Engine serial number, hull identification number or model year — as the catalog uses it.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='inventory.catalogsource')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='inventory.location')),
                ('variant', models.ForeignKey(blank=True, help_text="Which of the catalog's models this is, e.g. 4JH3E (A).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='inventory.catalogvariant')),
            ],
            options={
                'verbose_name_plural': 'equipment',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='equipment',
            field=models.ForeignKey(blank=True, help_text='The engine, hull or gear this job is on — used to check catalog parts fit it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='inventory.equipment'),
        ),
        migrations.CreateModel(
            name='CatalogRemarkCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('meaning', models.CharField(max_length=300)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remark_codes', to='inventory.catalogsource')),
            ],
            options={
                'ordering': ['catalog', 'code'],
                'constraints': [models.UniqueConstraint(fields=('catalog', 'code'), name='unique_catalog_remark_code')],
            },
        ),
        migrations.AddConstraint(
            model_name='catalogvariant',
            constraint=models.UniqueConstraint(fields=('catalog', 'code'), name='unique_catalog_variant_code'),
        ),
    ]
