# Generated by Django 6.1 on 2026-09-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_fitment_and_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogpartfitment',
            name='source',
            field=models.CharField(choices=[('import', 'Imported from the catalog'), ('manual', 'Entered by hand')], default='manual', help_text='Re-importing a catalog replaces only its own imported rows, never hand-entered ones.', max_length=10),
        ),
    ]
