# Generated by Django 6.1 on 2026-09-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_fitment_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqline',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rfqline',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
