"""
Django settings for djangoshipshape project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# Everything below that differs between a local checkout and the server is
# read from the environment, so a fresh clone still runs out of the box with
# no setup. On the server, set DJANGO_DEBUG=0, DJANGO_SECRET_KEY and
# DJANGO_ALLOWED_HOSTS (see README, "Running on a server").

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

# SECURITY WARNING: keep the secret key used in production secret!
# Falls back to a dev-only key so a fresh clone runs out of the box — but
# only while DEBUG is on, so the server can't accidentally run with it.
_DEV_SECRET_KEY = 'django-insecure-7*!idpkdfb@k*596vdu1)*!xkxtv+w=0dv=_2vj!yhu!6nl1&e'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', _DEV_SECRET_KEY)
if not DEBUG and SECRET_KEY == _DEV_SECRET_KEY:
    raise ImproperlyConfigured('Set DJANGO_SECRET_KEY when running with DJANGO_DEBUG=0.')

# Comma-separated, e.g. 'ionos-vps,100.118.115.74'. With DEBUG on, Django
# already allows localhost when this is empty.
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'treebeard',
    'inventory',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves collected static files straight from gunicorn — there's no
    # nginx in front of the app on the server.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Every page needs a login, as a backstop behind Tailscale in case a
    # device on the tailnet is lost. Opt a view out with @login_not_required.
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangoshipshape.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoshipshape.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
# Where `manage.py collectstatic` gathers admin/treebeard assets for
# WhiteNoise to serve when DEBUG is off.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# User-uploaded photos (items and locations)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Uploaded photos are downsized to fit within this many pixels on their
# longest side (see inventory.images.shrink_photo) — plenty to read a part
# number off, at a fraction of a phone camera's 3-5 MB.
PHOTO_MAX_DIMENSION = 1600

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'login'
# Stay logged in for 90 days, so snapping a photo on the phone doesn't
# mean logging in again every couple of weeks.
SESSION_COOKIE_AGE = 60 * 60 * 24 * 90

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Map Django's message levels onto Bootstrap 5 alert classes.
from django.contrib.messages import constants as message_constants  # noqa: E402

MESSAGE_TAGS = {
    message_constants.ERROR: 'danger',
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
